# Definindo variáveis de ambiente
DB_USERNAME = "yago.sampaio@assessorialpha.com"
DB_TOKEN = "Ya290620"

# Seções adicionais podem ser criadas conforme necessário
[some_section]
some_key = 2912

# Por exemplo, para armazenar seu token de acesso do Facebook
[facebook]
access_token = "EAAOUAvlbqgYBO9Np8hbuHo8XIURqEjRGuZCJUPMm6ZAzGbOQ2DxQRZBolzoD9hKfaDuySGF4fsh6rb229KL9b8YQ1hqsRQfKfq5GVeZBIGHJs8zUhaU8uyy9ydZCriZC7D4wFGk7RWHG3iZCQZC4ZCTKhKIkMKDUZChr9UKZAQc5zNxGpVBK4gP8Y5xOPyInvgUOOGyLWhqoHGvvrFgqlueNTiRPzXtcqZAX1o1c1QZDZD"
